Repository nanoframework/nanoframework.github.io, pull requests merged in 2022-02, with the labels that each got.

#119 Add API doc for `System.Device.Adc`
  azure-pipelines.yml
Labels: Type: enhancement, Area: Config-and-Build

#120 Add API docs for `nanoFramework.Aws.IoTCore.Devices`
  azure-pipelines.yml
Labels: Type: enhancement, Area: Config-and-Build

#122 Adding System.Net.Sockets.UdpClient
  azure-pipelines.yml
  content/architecture/class-libraries.md
  content/architecture/floating-point-calculations.md
  content/architecture/wire-protocol.md
  content/building/build-esp32.md
  content/building/build-in-visual-studio.md
  content/building/build-instructions.md
  content/building/build-nxp.md
  content/building/build-stm32.md
  content/building/cmake-tools-cmake-variants.md
  content/contributing/contributing-workflow.md
  content/contributing/developing-native/vscode-debug-instructions.md
  content/maintainers/creating-a-new-repo.md
  content/reference-targets/esp32-s2.md
Labels: Area: Config-and-Build

#123 Update simplifications-and-trade-offs
  content/architecture/simplifications-and-trade-offs.md
Labels: Type: enhancement

#124 Remove ESP32 firmware doc
  content/esp32/esp32_firmware_versions.md
  content/esp32/index.md
  content/toc.yml
Labels: Type: enhancement
