Repository nanoframework/nanoframework.github.io, pull requests merged in 2023-08, with the labels that each got.

#178 Fix improve doc links not working for dynamically generated pages
  azure-pipelines.yml
Labels: Type: enhancement, Area: Config-and-Build

#181 Fix replace link on documentation when devices has not been built
  azure-pipelines.yml
Labels: Area: Config-and-Build

#182 Fix fw packages labels
  content/community-targets/GHI_FEZ_CERB40_NF.md
  content/community-targets/I2M_ELECTRON_NF.md
  content/community-targets/I2M_OXYGEN_NF.md
  content/community-targets/NESHTEC-NeshNode.md
  content/community-targets/ST_NUCLEO144_F412ZG_NF.md
  content/community-targets/ST_NUCLEO64_F401RE_NF.md
  content/community-targets/ST_NUCLEO64_F411RE_NF.md
  content/community-targets/brainpad2.md
  content/community-targets/mbn-quail.md
  content/community-targets/netduino3-wifi.md
  content/community-targets/pybstick2x.md
  content/community-targets/st-nucleo144-f746zg.md
  content/community-targets/st_nucleo144_f439zi.md
  content/community-targets/stm32f4-discovery.md
  content/community-targets/stm32f411-discovery.md
  content/community-targets/ti-cc1352p1-launchxl.md
  content/reference-targets/st-nucleo64-f091rc.md
  content/reference-targets/ti-cc1352r1-launchxl.md
Labels: Type: enhancement
